package by.cp.feedback.mechanism.bot.exception

class FromNotFoundException : FeedbackBotException("From not found")